

title = ""
theme = "not-much"
languageCode = "en-us"
baseURL = "https://maniurek.github.io/Maciej-Wozniak/"s

[markup]
  [markup.highlight]
    style = 'cool'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
theme = "dark"
palette = "cool"
showThemeNotice = true
showPostsSummary = true

# Giscus Comment System
[params.giscus]
repository = "username/repository"
repositoryId = "repositoryId"
categoryName = "categoryName"
categoryId = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
language = "en"
lazyLoading = true

# Navigation
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "posts"
    name = "projects"
    title = "projects"
    url = "/posts"
    weight = 2
  
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about"
    weight = 3
	
